import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "./components/Navbar";
import NextAuthProvider from "./SessionProvider"; // ✅ client wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Wrap with SessionProvider inside a Client Component */}
        <NextAuthProvider>
          <div className="flex">
            <Toaster />
            <Navbar />
            <main className="flex-1 p-6">{children}</main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
